server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-service/v1/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/inventory-service/v1/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment-service/v1/**
        - id: invoice-service
          uri: lb://INVOICE-SERVICE
          predicates:
            - Path=/invoice-service/v1/**
#    consul:
#      discovery:
#        instance-id: ${spring.application.name}:${server.port}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${random.int[1,999999]}