package com.example.order.enums;

import lombok.Getter;

@Getter
public enum OrderStatus {

	ORDER_CREATED,
	INVENTORY_PENDING,
	INVENTORY_APPROVED,
	INVENTORY_CANCELATION_PENDING,
	INVENTORY_CANCELLED,
	PAYMENT_APPROVED,
	PAYMENT_PENDING,
	PAYMENT_CANCELATION_PENDING,
	PAYMENT_CANCELLED,
	INVOICE_PENDING,
	INVOICE_APPROVED,
	INVOICE_CANCELATION_PENDING,
	INVOICE_CANCELLED,
	ORDER_CANCELLED,
	ORDER_APPROVED,
	UNKNOWN
	;

}
